# Generated by Django 4.2.3 on 2023-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_num', models.IntegerField()),
                ('ward_name', models.CharField(max_length=150, null=True)),
                ('area_name', models.CharField(max_length=150, null=True)),
                ('ward_president', models.CharField(max_length=150, null=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
