# Generated by Django 4.1.5 on 2023-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0002_alter_ward_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150, null=True)),
                ('start_date', models.CharField(max_length=150, null=True)),
                ('end_date', models.CharField(max_length=150, null=True)),
                ('notes', models.TextField(max_length=150, null=True)),
            ],
        ),
    ]
