# Generated by Django 4.1.5 on 2023-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0004_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
