# Generated by Django 4.1.5 on 2023-07-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0006_hall_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
