# Generated by Django 4.1.5 on 2023-07-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0008_rename_donation_type_donation_donation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('rupees', models.DateField(max_length=150, null=True)),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.type_donation')),
            ],
        ),
    ]
