# Generated by Django 4.1.5 on 2023-07-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0010_rename_hall_hall_booking_hall_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall_booking',
            name='hall_id',
        ),
    ]
