# Generated by Django 4.1.5 on 2023-07-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0012_hall_booking_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150, null=True)),
                ('page_number', models.CharField(max_length=150, null=True)),
                ('diocese', models.CharField(max_length=150, null=True)),
                ('parish', models.CharField(max_length=150, null=True)),
                ('house_name', models.CharField(max_length=150, null=True)),
                ('place', models.CharField(max_length=150, null=True)),
                ('post_office', models.CharField(max_length=150, null=True)),
                ('pincode', models.CharField(max_length=150, null=True)),
                ('tel', models.CharField(max_length=150, null=True)),
                ('mob', models.CharField(max_length=150, null=True)),
                ('head_of_family', models.CharField(max_length=150, null=True)),
                ('female_head', models.CharField(max_length=150, null=True)),
                ('seperated_year_family', models.CharField(max_length=150, null=True)),
                ('joining_date', models.CharField(max_length=150, null=True)),
                ('income_status', models.CharField(max_length=150, null=True)),
                ('number_of_priests', models.CharField(max_length=150, null=True)),
                ('number_of_sisters', models.CharField(max_length=150, null=True)),
                ('ward_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.ward')),
            ],
        ),
    ]
