# Generated by Django 4.1.5 on 2023-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0013_family_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_details',
            name='joining_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='number_of_priests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='number_of_sisters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='seperated_year_family',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
