# Generated by Django 4.1.5 on 2023-07-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0016_remove_deceased_persons_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased_persons',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.family_details'),
        ),
        migrations.AlterField(
            model_name='deceased_persons',
            name='relation',
            field=models.CharField(choices=[('Female_head', 'Female_head'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grand Son', 'Grand Son'), ('Grand Daughter', 'Grand Daughter')], max_length=150, null=True),
        ),
    ]
