# Generated by Django 4.1.5 on 2023-07-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0017_deceased_persons_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('father_name', models.CharField(max_length=150, null=True)),
                ('mother_name', models.CharField(max_length=150, null=True)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Married', max_length=150)),
                ('relation', models.CharField(choices=[('Family Head Male', 'Family Head Male'), ('Family Head Female', 'Family Head Female'), ('Son', 'son'), ('Daughter', 'Daughter'), ('Son in Law', 'Son in Law'), ('Daughter in Law', 'Daughter'), ('Grand Son', 'Grand Son'), ('Grand Daughter', 'Grand Daughter')], default='Family Head Male', max_length=150, null=True)),
                ('Land_no', models.CharField(max_length=150, null=True)),
                ('Mob_no', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('blood_group', models.CharField(max_length=150, null=True)),
                ('Qualification', models.CharField(choices=[('Below SSLC', 'Below SSLC'), ('SSLC', 'SSLC'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('PG', 'PG'), ('Phd', 'Phd')], default='Degree', max_length=150)),
                ('working_status', models.CharField(choices=[('Govt Job', 'Govt Job'), ('Private Job', 'Private Job'), ('Business', 'Business'), ('Abroad', 'Abroad'), ('Studying', 'Studying')], default='Private Job', max_length=150, null=True)),
                ('place', models.CharField(max_length=150, null=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.family_details')),
            ],
        ),
    ]
