# Generated by Django 4.1.5 on 2023-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0018_personal_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baptism_name', models.CharField(max_length=150, null=True)),
                ('Reg_number', models.IntegerField(max_length=150, null=True)),
                ('baptism_date', models.CharField(max_length=150, null=True)),
                ('baptism_place', models.CharField(max_length=150, null=True)),
                ('sacrement', models.CharField(max_length=150, null=True)),
                ('godfather_name', models.CharField(max_length=150, null=True)),
                ('gf_baptism_name', models.CharField(max_length=150, null=True)),
                ('gf_diocese', models.CharField(max_length=150, null=True)),
                ('gf_parish', models.CharField(max_length=150, null=True)),
                ('gf_house_name', models.CharField(max_length=150, null=True)),
                ('godmother_name', models.CharField(max_length=150, null=True)),
                ('gm_baptism_name', models.CharField(max_length=150, null=True)),
                ('gm_diocese', models.CharField(max_length=150, null=True)),
                ('gm_parish', models.CharField(max_length=150, null=True)),
                ('gm_house_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Qualification',
            field=models.CharField(choices=[('Below SSLC', 'Below SSLC'), ('SSLC', 'SSLC'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Above Graduate', 'Above Graduate')], default='Degree', max_length=150),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], default='A+', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Widow/Widower', 'Widow/Widower')], default='Married', max_length=150),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='relation',
            field=models.CharField(choices=[('Family Head Male', 'Family Head Male'), ('Family Head Female', 'Family Head Female'), ('Son', 'son'), ('Daughter', 'Daughter'), ('Son in Law', 'Son in Law'), ('Daughter in Law', 'Daughter in Law'), ('Grand Son', 'Grand Son'), ('Grand Daughter', 'Grand Daughter')], default='Family Head Male', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='working_status',
            field=models.CharField(choices=[('Govt Job', 'Govt Job'), ('Private Job', 'Private Job'), ('Business', 'Business'), ('Abroad', 'Abroad'), ('Studying', 'Studying'), ('Others', 'Others')], default='Private Job', max_length=150, null=True),
        ),
    ]
