# Generated by Django 4.1.5 on 2023-07-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0019_baptism_details_alter_personal_details_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptism_details',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.family_details'),
        ),
    ]
