# Generated by Django 4.1.5 on 2023-07-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0020_baptism_details_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptism_details',
            name='baptism_date',
            field=models.DateField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='confirmation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.CharField(max_length=150, null=True)),
                ('confirmation_place', models.CharField(max_length=150, null=True)),
                ('sacrement', models.CharField(max_length=150, null=True)),
                ('godfather_name', models.CharField(max_length=150, null=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.family_details')),
            ],
        ),
    ]
