# Generated by Django 4.1.5 on 2023-07-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0023_rename_sacrement_baptism_details_celebrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased_persons',
            name='funeral_date',
            field=models.DateField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=150)),
                ('rupees', models.CharField(default=50, max_length=150)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Church_app.family_details')),
            ],
        ),
    ]
