# Generated by Django 4.1.5 on 2023-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church_app', '0024_deceased_persons_funeral_date_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall_booking',
            name='end_date',
        ),
        migrations.AddField(
            model_name='hall_booking',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening')], default='Male', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2023')], default='2023', max_length=150),
        ),
    ]
